-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 11:20:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancadb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bancadb` ;

-- -----------------------------------------------------
-- Table `bancadb`.`cuentabancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancadb`.`cuentabancaria` (
  `idCuentaBancaria` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(60) NULL DEFAULT NULL,
  `idVendedor` INT NULL DEFAULT NULL,
  `alias` VARCHAR(60) NULL DEFAULT NULL,
  `cbu` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCuentaBancaria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancadb`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancadb`.`tarjeta` (
  `idTarjeta` INT NOT NULL AUTO_INCREMENT,
  `idComprador` INT NULL DEFAULT NULL,
  `limiteMensual` DECIMAL(10,2) NULL DEFAULT NULL,
  `saldo` DECIMAL(10,2) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `cvc` VARCHAR(3) NULL DEFAULT NULL,
  `tipo` VARCHAR(60) NULL DEFAULT NULL,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `vencimiento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idTarjeta`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
